"""Add tag, comment, and relationships

Revision ID: c19965811874
Revises: 2ead2e8ec02f
Create Date: 2025-11-01 13:32:46.482635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19965811874'
down_revision: Union[str, Sequence[str], None] = '2ead2e8ec02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('comment',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_soft_deleted', sa.Boolean(), nullable=False),
    sa.Column('soft_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_comment_author_id_user')),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], name=op.f('fk_comment_parent_comment_id_comment')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_comment_post_id_post')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_is_soft_deleted'), ['is_soft_deleted'], unique=False)

    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_tags_post_id_post')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_post_tags_tag_id_tag')),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', 'id', name=op.f('pk_post_tags'))
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_soft_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('soft_deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(length=10000),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_post_is_soft_deleted'), ['is_soft_deleted'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_post_author_id_user'), 'user', ['author_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_soft_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('soft_deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_is_soft_deleted'), ['is_soft_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_soft_deleted'))
        batch_op.drop_column('soft_deleted_at')
        batch_op.drop_column('is_soft_deleted')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_author_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_post_is_soft_deleted'))
        batch_op.alter_column('content',
               existing_type=sa.Text(length=10000),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('soft_deleted_at')
        batch_op.drop_column('is_soft_deleted')
        batch_op.drop_column('author_id')
        batch_op.drop_column('title')

    op.drop_table('post_tags')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_is_soft_deleted'))

    op.drop_table('comment')
    op.drop_table('tag')
    # ### end Alembic commands ###
